[project]
authors = [{name = "raceychan", email = "raceychan@gmail.com"}]
description = "Add a short description here"
name = "ididi"
requires-python = ">= 3.12"
version = "0.1.0"

[tool.setuptools]
py-modules = ["didi"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.environments]
default = {solve-group = "default"}
publish = {features = ["publish"], solve-group = "default"}
test = {features = ["test"], solve-group = "default"}

[tool.pixi.pypi-dependencies]
ididi = {path = ".", editable = true}

[tool.pixi.dependencies]
python = ">=3.12"

[tool.pixi.feature.test.dependencies]
pytest = ">=8.3.3"

[tool.pixi.feature.publish.dependencies]
hatch = ">=1.13.0,<2"
twine = ">=5.1.1,<6"

[tool.pixi.feature.publish.tasks]
# Build into a wheel using hatch
build = {cmd = "hatch build", inputs = ["didi/*"], outputs = ["dist/*"]}
# Upload to custom GCP registry using twine
check = {cmd = "twine check"}
publish = {cmd = "twine upload --skip-existing dist/*", depends-on = [
  "build",
]}
test-publish = {cmd = "twine upload --repository testpypi --skip-existing dist/"}
